[package]
name = "rusty-roots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0"
colored = "2.1"
mime_guess = "2.0"
mime = "0.3"
globset = "0.4"
log = "0.4"
env_logger = "0.11"